### PR TITLE
feat: osquery collection increase

### PR DESCRIPTION
**Pull request by stinkingpig**

### CODE REVIEW

**Review by arthur-observe — APPROVED** [review]
Fixing tests now - state got twisted in ci

telegraf is in midst of rotating signing keys - I presume tests will work again tomorrow - https://www.influxdata.com/blog/linux-package-signing-key-rotation/

**Review by arthur-observe — CHANGES_REQUESTED** [review]
Please rebase on main to uptake changes for telegraf repo key

**Comment by arthur-observe** [comment]
If you get a fail on the RHEL on GCP ignore it

**Comment by arthur-observe** [comment]
image

**Review by arthur-observe — APPROVED** [review]

**Review by jlebaugh — APPROVED** [review]

**Pull request merged**
